dist: xenial
language: bash

  
before_script:
  - sudo apt install xvfb
  - chmod +x tma_v2.1-setup.sh

services:
  - xvfb


script:
    - xvfb-run --server-args="-screen 0 1024x768x24" make test
    - ./tma_v2.1-setup.sh
    - tma
