language: bash

services:
  - xvfb
  
before_script:
  - sudo apt install xvfb xserver-common x11-xkb-utils libgl1-mesa-dri
  - sleep 5
  - chmod +x tma_v2.1-setup.sh

script:
    - xvfb-run --server-args="-screen 0 1024x768x24" make test
    - ./tma_v2.1-setup.sh
    - tma
