dist: xenial
language: bash

services:
  - xvfb
  
before_script:
  - chmod +x tma_v2.1-setup.sh

script:
    - xvfb-run --server-args="-screen 0 1024x768x24" make test
    - ./tma_v2.1-setup.sh
    - tma
