language: python
python:
  - "2.7"

env:
  global:
    - DISPLAY=:99

sudo: required
addons:
  apt:
  packages:
    - python-tk
    - xvfb
    
before_script:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
    
script:
  - python tma.py
  - sleep 5
  - exit
