
language: bash
os: linux
sudo: required
dist: xenial

addons:
  apt:
    packages:
    - xvfb
    
services:
  - xvfb
  
before_script:
  - chmod +x tma_v2.1-setup.sh
  
script:
  - ./tma_v2.1-setup.sh
  - tma
