
language: bash
os: linux
sudo: required
dist: xenial

addons:
  apt:
  sources:
    - sourceline: "deb http://us.archive.ubuntu.com/ubuntu/ xenial main universe"
  packages:
    - xvfb
    
env:
  global:
    - DISPLAY=:99

before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/xvfb -- :99 -ac -screen 0 1280x1024x24"
  - sleep 3

before_script:
    - chmod +x tma_v2.1-setup.sh
    
script:
    - ./tma_v2.1-setup.sh
    - tma
