language: python
python:
  - "2.7"

env:
  global:
    - DISPLAY=:99

sudo: required
addons:
  apt:
  packages:
    - python-tk
    - xvfb
    
script:
  - xvfb-run --auto-servernum --server-num=1 python tma.py
