
language: bash
os: linux
sudo: required
dist: xenial

addons:
  apt:
    packages:
    - xvfb
  
# set the X11 Display variable as a global environment variable
env:
  global:
    - DISPLAY=:99
    
# start xvfb using DISPLAY port
before_script:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- $DISPLAY -ac -screen 0 1280x1024x24"
  - sleep 3
    
script:
  - chmod +x tma_v2.1-setup.sh
  - ./tma_v2.1-setup.sh
  - xvfb-run --server-args="-screen 0 1280x1024x24" tma
