
language: bash
os: linux
sudo: required
dist: xenial

addons:
  apt:
    packages:
    - xvfb
    
env:
  global:
    - DISPLAY=:99
    
script:
    - xvfb-run --server-args="-screen 0 1024x768x24" make test
