
language: bash
os: linux
sudo: required
dist: xenial

addons:
  apt:
  sources:
    - sourceline: "deb http://us.archive.ubuntu.com/ubuntu/ xenial main universe"
  packages:
    - xvfb
    
env:
  global:
    - DISPLAY=:99

before_script:
    - chmod +x tma_v2.1-setup.sh
    
script:
    - ./tma_v2.1-setup.sh
    - tma
